{
	"msg": "操作成功",
	"data": {
		"result": "1",
		"orderBrief": {
			"examineImage": null,
			"orderNo": "1017581126141603725",
			"totalPrice": 40.0,
			"parkImage": null,
			"keepPassword": null,
			"orderStatus": 4,
			"techName": null,
			"techPhone": null,
			"deviceNo": null,
			"serviceName": "回家普洗",
			"completeImage": null,
			"vehicleLocation": "洗车店左侧",
			"deviceAddress": null,
			"appointmentTime": null,
			"servicePrice": 0.0,
			"createTime": null,
			"carNo": null,
			"serviceId": "1",
			"techGraded": null,
			"payStatus": 1,
			"techId": null,
			"devicePassword": null
		},
		"orgName": "军产地产",
		"cityName": "深圳市",
		"balance": 92000.0,
		"bannerList": [{
			"bannerId": "4",
			"bannerUrl": "http://chegongfang.oss-cn-shenzhen.aliyuncs.com/banner/20171101205308_101.jpg",
			"bannerLink": "http://wx.huijiayangche.com/static/t.html"
		}, {
			"bannerId": "5",
			"bannerUrl": "http://chegongfang.oss-cn-shenzhen.aliyuncs.com/banner/84961782696926116.jpg",
			"bannerLink": "http://wx.huijiayangche.com/static/c.html"
		}, {
			"bannerId": "6",
			"bannerUrl": "\r\nhttp://chegongfang.oss-cn-shenzhen.aliyuncs.com/banner/20171101205440_103.jpg",
			"bannerLink": "http://wx.huijiayangche.com/static/d.html"
		}],
		"dinnerList": [{
			"goodsId": 1,
			"goodsName": "回家普洗",
			"goodsNum": "4",
			"dinnerMoney": 0.0,
			"dinnerId": 0,
			"dinnerName": null
		}, {
			"goodsId": 2,
			"goodsName": "回家精洗",
			"goodsNum": "10",
			"dinnerMoney": 0.0,
			"dinnerId": 0,
			"dinnerName": null
		}, {
			"goodsId": 3,
			"goodsName": "车内环保干洗",
			"goodsNum": "5",
			"dinnerMoney": 0.0,
			"dinnerId": 0,
			"dinnerName": null
		}, {
			"goodsId": 4,
			"goodsName": "车内环保消毒",
			"goodsNum": "6",
			"dinnerMoney": 0.0,
			"dinnerId": 0,
			"dinnerName": null
		}, {
			"goodsId": 9,
			"goodsName": "回家标准打蜡",
			"goodsNum": "6",
			"dinnerMoney": 0.0,
			"dinnerId": 0,
			"dinnerName": null
		}],
		"cityId": "440300",
		"userId": "66",
		"orgId": 6,
		"token": "5f9e04d9efef4d88961bb58045531cd060cc5d5e84284e368bb61ed6ec862371"
	},
	"flag": "1"
}
